In [1]:
# import necessary libraries
import numpy as np
import tensorflow as tf

### Training Phase

In [2]:
# load dataset
with open("/content/cricket.txt", 'r', encoding='utf-8') as file:
    cricket_history = file.read()

In [3]:
cricket_history[:500]

'Cricket history is particularly murky and vague as to the exact origins of the game, it is believed to have been born in England in the late middle ages.\n\nEdward III banned a game similar to cricket in 1369, ‘pila baculorea’ or ‘club ball’ as it was known, as he saw it as being a distraction to his war effort.\n\nDerek Birley in his wonderful book, ‘A Social History of English Cricket’ suggests the game came to England with the French during the time of the Norman Invasion, that their word ‘crique'

In [4]:
tokenizer = tf.keras.preprocessing.text.Tokenizer()
tokenizer.fit_on_texts([cricket_history])

In [5]:
tokenizer.get_config()['filters']

'!"#$%&()*+,-./:;<=>?@[\\]^_`{|}~\t\n'

In [6]:
tokenizer.get_config()['word_counts']

'{"cricket": 35, "history": 2, "is": 8, "particularly": 2, "murky": 1, "and": 47, "vague": 1, "as": 25, "to": 45, "the": 148, "exact": 1, "origins": 1, "of": 48, "game": 22, "it": 22, "believed": 1, "have": 4, "been": 4, "born": 2, "in": 57, "england": 15, "late": 1, "middle": 1, "ages": 1, "edward": 3, "iii": 2, "banned": 1, "a": 22, "similar": 2, "1369": 1, "\\u2018pila": 1, "baculorea\\u2019": 1, "or": 5, "\\u2018club": 1, "ball\\u2019": 1, "was": 15, "known": 1, "he": 1, "saw": 7, "being": 8, "distraction": 1, "his": 2, "war": 1, "effort": 1, "derek": 1, "birley": 1, "wonderful": 1, "book": 1, "\\u2018a": 1, "social": 1, "english": 6, "cricket\\u2019": 3, "suggests": 1, "came": 1, "with": 16, "french": 1, "during": 2, "time": 5, "norman": 1, "invasion": 2, "that": 9, "their": 4, "word": 3, "\\u2018criquet\\u2019": 1, "dialect": 1, "name": 1, "for": 19, "variation": 1, "club": 4, "ball": 3, "had": 9, "sought": 2, "eradicate": 1, "there": 3, "record": 1, "\\u2018creag\\u2019": 2, "de

In [7]:
tokenizer.word_index

{'the': 1,
 'in': 2,
 'of': 3,
 'and': 4,
 'to': 5,
 'cricket': 6,
 'as': 7,
 'game': 8,
 'it': 9,
 'a': 10,
 'for': 11,
 'with': 12,
 'were': 13,
 'england': 14,
 'was': 15,
 'its': 16,
 'played': 17,
 'by': 18,
 'that': 19,
 'had': 20,
 'at': 21,
 'is': 22,
 'being': 23,
 'games': 24,
 'saw': 25,
 'they': 26,
 'new': 27,
 'australia': 28,
 'english': 29,
 'playing': 30,
 'first': 31,
 'an': 32,
 'be': 33,
 'between': 34,
 'from': 35,
 'technology': 36,
 'or': 37,
 'time': 38,
 'this': 39,
 'aristocracy': 40,
 'recorded': 41,
 'century': 42,
 'two': 43,
 'on': 44,
 'after': 45,
 'bowling': 46,
 'twenty': 47,
 'have': 48,
 'been': 49,
 'their': 50,
 'club': 51,
 'them': 52,
 'classes': 53,
 'teams': 54,
 'up': 55,
 'match': 56,
 'players': 57,
 'into': 58,
 'began': 59,
 'spread': 60,
 'south': 61,
 'international': 62,
 'only': 63,
 'edward': 64,
 'cricket’': 65,
 'word': 66,
 'ball': 67,
 'there': 68,
 'play': 69,
 'men': 70,
 'way': 71,
 'seen': 72,
 'side': 73,
 'best': 74,
 'becom

In [8]:
input_sequences = []
for sentence in cricket_history.split('\n'):
    token_list = tokenizer.texts_to_sequences([sentence])[0]
    for i in range(1, len(token_list)):
        sequence = token_list[:i+1]
        input_sequences.append(sequence)

In [9]:
input_sequences[:5]

[[6, 93],
 [6, 93, 22],
 [6, 93, 22, 94],
 [6, 93, 22, 94, 178],
 [6, 93, 22, 94, 178, 4]]

In [10]:
max_length = max([len(input_sequence) for input_sequence in input_sequences])
max_length

55

In [11]:
# add padding
input_sequences = np.array(tf.keras.preprocessing.sequence.pad_sequences(input_sequences, maxlen=max_length, padding='pre'))

In [12]:
input_sequences[1]

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  6, 93, 22], dtype=int32)

In [13]:
# divide dataset into feature set (X) and labels (y)
X = input_sequences[:, :-1]
y = input_sequences[:, -1]

In [14]:
X[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 6], dtype=int32)

In [15]:
y

array([ 93,  22,  94, ...,  38, 177, 622], dtype=int32)

In [16]:
# number of words
num_classes = len(tokenizer.word_index)+1

In [17]:
# one-hot encoding labels
y = np.array(tf.keras.utils.to_categorical(y, num_classes=num_classes))

In [18]:
y[1]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [19]:
# model building
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Embedding(num_classes, 80, input_length=max_length-1))
model.add(tf.keras.layers.LSTM(100))
model.add(tf.keras.layers.Dense(num_classes, activation='softmax'))

In [20]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 54, 80)            49840     
                                                                 
 lstm (LSTM)                 (None, 100)               72400     
                                                                 
 dense (Dense)               (None, 623)               62923     
                                                                 
Total params: 185163 (723.29 KB)
Trainable params: 185163 (723.29 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [21]:
# compile the model
model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

In [22]:
# model training
history = model.fit(X, y, epochs=100)

Epoch 1/100
47/47 [==============================] - 8s 101ms/step - loss: 6.1235 - accuracy: 0.0823
Epoch 2/100
47/47 [==============================] - 3s 58ms/step - loss: 5.6412 - accuracy: 0.0911
Epoch 3/100
47/47 [==============================] - 2s 52ms/step - loss: 5.5605 - accuracy: 0.0911
Epoch 4/100
47/47 [==============================] - 2s 49ms/step - loss: 5.5054 - accuracy: 0.0911
Epoch 5/100
47/47 [==============================] - 2s 47ms/step - loss: 5.4318 - accuracy: 0.0911
Epoch 6/100
47/47 [==============================] - 3s 58ms/step - loss: 5.3507 - accuracy: 0.0911
Epoch 7/100
47/47 [==============================] - 3s 57ms/step - loss: 5.2707 - accuracy: 0.0911
Epoch 8/100
47/47 [==============================] - 2s 47ms/step - loss: 5.1952 - accuracy: 0.1026
Epoch 9/100
47/47 [==============================] - 2s 46ms/step - loss: 5.1103 - accuracy: 0.1221
Epoch 10/100
47/47 [==============================] - 2s 47ms/step - loss: 5.0263 - accuracy: 0.130

### Prediction Phase

In [23]:
input_text = "cricket begin"
for i in range(6):
    token_list = tokenizer.texts_to_sequences([input_text])[0]
    token_list = tf.keras.preprocessing.sequence.pad_sequences([token_list], maxlen=max_length-1, padding='pre')
    predicted = np.argmax(model.predict(token_list), axis=-1)
    output_word = ""
    for word, index in tokenizer.word_index.items():
        if index == predicted:
            output_word = word
            break
    input_text += " " + output_word

print(input_text)

1/1 [==============================] - 0s 33ms/step
cricket begin the west indies and india by
